/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import javax.accessibility.AccessibleContext;
import javax.swing.JLabel;

/**
 *
 * @author rtorress1400
 */
public class PArticulo extends javax.swing.JPanel {

    /**
     * Creates new form PArticulo
     */
    public PArticulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JA_Nombre = new javax.swing.JLabel();
        JA_Desc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JA_Cant = new javax.swing.JLabel();
        JA_img1 = new javax.swing.JLabel();
        JA_img2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(200, 100));
        setMinimumSize(new java.awt.Dimension(200, 100));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(200, 100));

        JA_Nombre.setText("jLabel1");

        JA_Desc.setText("jLabel1");

        jLabel1.setText("Cantidad");

        JA_Cant.setText("jLabel2");

        JA_img1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JA_img1.setMaximumSize(new java.awt.Dimension(75, 75));
        JA_img1.setMinimumSize(new java.awt.Dimension(75, 75));
        JA_img1.setPreferredSize(new java.awt.Dimension(75, 75));

        JA_img2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JA_img2.setMaximumSize(new java.awt.Dimension(75, 75));
        JA_img2.setMinimumSize(new java.awt.Dimension(75, 75));
        JA_img2.setPreferredSize(new java.awt.Dimension(75, 75));

        jLabel2.setText("Descripcion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(JA_Cant))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JA_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(JA_img2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(JA_Nombre))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JA_Desc)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JA_Nombre)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JA_img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JA_img2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JA_Desc)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JA_Cant))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getJA_Cant() {
        return JA_Cant.getText();
    }


    public void setJA_Cant(String JA_Cant) {
        this.JA_Cant.setText(JA_Cant);
    }

    public String getJA_Desc() {
        return JA_Desc.getText();
    }

    public void setJA_Desc(String JA_Desc) {
        this.JA_Desc.setText(JA_Desc);
    }

    public String getJA_Nombre() {
        return JA_Nombre.getText();
    }

    public void setJA_Nombre(String JA_Nombre) {
        this.JA_Nombre.setText(JA_Nombre);
    }

    public JLabel getJA_img1() {
        return JA_img1;
    }

    public void setJA_img1(JLabel JA_img1) {
        this.JA_img1 = JA_img1;
    }

    public JLabel getJA_img2() {
        return JA_img2;
    }

    public void setJA_img2(JLabel JA_img2) {
        this.JA_img2 = JA_img2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JA_Cant;
    private javax.swing.JLabel JA_Desc;
    private javax.swing.JLabel JA_Nombre;
    private javax.swing.JLabel JA_img1;
    private javax.swing.JLabel JA_img2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
